import os
import json
import logging
import requests
from typing import Dict, Any

logger = logging.getLogger(__name__)

class NemotronService:
    """Service to interact with AI Models (NVIDIA/HuggingFace) for ML signal explanations."""

    def __init__(self):
        pass

    def _get_config(self):
        raw_nv = os.getenv("NVIDIA_API_KEY")
        nv_key = raw_nv.strip() if raw_nv else None
        
        raw_hf = os.getenv("HUGGINGFACE_API_KEY") or os.getenv("HF_TOKEN")
        hf_key = raw_hf.strip() if raw_hf else None
        
        if nv_key:
            return {
                "api_key": nv_key,
                "base_url": "https://integrate.api.nvidia.com/v1/chat/completions",
                "model": "nvidia/nemotron-3-nano-30b-a3b",
                "is_hf": False
            }
        elif hf_key:
            return {
                "api_key": hf_key,
                "base_url": "https://router.huggingface.co/v1/chat/completions",
                "model": "meta-llama/Llama-3.1-8B-Instruct",
                "is_hf": True
            }
        return None

    def analyze_signal(self, symbol: str, context: Dict[str, Any]) -> Dict[str, Any]:
        config = self._get_config()
        
        fallback_response = {
            "summary": "AI Analyst temporarily unavailable.",
            "supporting_factors": [],
            "risk_factors": [],
            "reasoning": f"DEBUG INFO - CONFIG FOUND: {bool(config)}. The server could not connect to the AI model."
        }

        if not config:
            return fallback_response

        system_prompt = (
          "You are an expert quantitative market analyst. "
"You are given a trading signal that has ALREADY been generated by a machine learning model, "
"including its decision (ACCEPT/AVOID), probability, entry price, exit price, and P&L. "
"Your ONLY job is to explain, in plain language, the market reasoning that likely supports this "
"pre-calculated signal. "
"\n\n"
"HARD CONSTRAINTS:\n"
"- Treat the ML model's decision, probability, entry price, exit price, and P&L as ground truth. "
"Never contradict, second-guess, revise, or recompute any of them.\n"
"- Do NOT propose your own entry price, exit price, P&L, probability, or ACCEPT/AVOID decision, "
"even implicitly (e.g. do not say a different price 'would be better').\n"
"- Do NOT add trading advice, recommendations, or instructions beyond explaining the given signal.\n"
"- If the provided data is incomplete, contradictory, or insufficient to explain confidently, "
"say so plainly in the \"reasoning\" field instead of inventing a justification.\n"
"- Base your explanation only on the data provided to you. Do not fabricate indicators, news, "
"or price levels that were not given.\n"
"\n"
"OUTPUT FORMAT:\n"
"Respond with ONLY a single valid JSON object — no markdown code fences, no commentary before or "
"after, no trailing commas — matching this schema exactly:\n"
"{\n"
'  "summary": "1-2 sentences summarizing the technical setup.",\n'
'  "supporting_factors": ["array of concise bullish/bearish points supporting the decision"],\n'
'  "risk_factors": ["array of concise risks or opposing indicators"],\n'
'  "reasoning": "2-3 paragraphs explaining the market context and why the ML model likely made this decision."\n'
"}"
        )

        user_prompt = f"Analyze this ML Signal for {symbol}:\n{json.dumps(context, indent=2)}"

        headers = {
            "Authorization": f"Bearer {config['api_key']}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "model": config['model'],
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "temperature": 1,
            "top_p": 1,
            "max_tokens": 8192
        }

        try:
            response = requests.post(config['base_url'], headers=headers, json=payload, timeout=60.0)
            response.raise_for_status()
            
            result_data = response.json()
            result_text = result_data['choices'][0]['message']['content']
            
            import re
            text_without_think = re.sub(r'<think>.*?</think>', '', result_text, flags=re.DOTALL)
            json_match = re.search(r'\{.*\}', text_without_think, re.DOTALL)
            
            if json_match:
                parsed = json.loads(json_match.group(0))
                return {
                    "summary": parsed.get("summary") or parsed.get("Summary") or "Summary not provided.",
                    "supporting_factors": parsed.get("supporting_factors") or parsed.get("Supporting_Factors") or parsed.get("Supporting Factors") or [],
                    "risk_factors": parsed.get("risk_factors") or parsed.get("Risk_Factors") or parsed.get("Risk Factors") or [],
                    "reasoning": parsed.get("reasoning") or parsed.get("Reasoning") or "Reasoning not provided."
                }
            else:
                logger.error(f"Failed to find JSON block in model response: {result_text}")
                raise ValueError(f"No JSON block found in response. Raw response: {result_text[:200]}")

        except requests.exceptions.HTTPError as e:
            error_body = ""
            try:
                error_body = e.response.text
            except Exception:
                pass
            logger.error(f"AI request failed with HTTPError: {e}, Response: {error_body}")
            fallback_response["reasoning"] = f"AI request failed: {str(e)}. Response: {error_body}"
            return fallback_response
        except json.JSONDecodeError as e:
            logger.error(f"AI returned invalid JSON: {e}. Raw response: {result_text}")
            fallback_response["reasoning"] = f"Received invalid response format from AI Analyst: {str(e)}. Raw response: {result_text[:400]}"
            return fallback_response
        except Exception as e:
            logger.error(f"AI analysis failed: {e}")
            fallback_response["reasoning"] = f"AI request failed: {str(e)}"
            return fallback_response
